mappings:
  GridFieldBulkActionDeleteHandler: Violet88\BulkManager\BulkAction\DeleteHandler
  GridFieldBulkActionEditHandler: Violet88\BulkManager\BulkAction\EditHandler
  GridFieldBulkActionHandler: Violet88\BulkManager\BulkAction\Handler
  GridFieldBulkActionUnlinkHandler: Violet88\BulkManager\BulkAction\UnlinkHandler
  GridFieldBulkManager: Violet88\BulkManager\BulkManager
  BulkUploadField: Violet88\BulkUpload\BulkUploadField
  GridFieldBulkImageUpload: Violet88\BulkUpload\GridFieldBulkImageUpload
  GridFieldBulkUpload: Violet88\BulkUpload\BulkUploader
  GridFieldBulkUpload_Request: Violet88\BulkUpload\BulkUploadHandler
