// DO NOT MODIFY. Generated by build task.
// Contribute here: https://www.transifex.com/projects/p/gridfieldbulkeditingtools/
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
  if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
  ss.i18n.addDictionary('nl', {
    "GridFieldBulkTools.FINISH_CONFIRM": "Er zijn niet-opgeslagen wijzigingen.\n\nDoorgaan zal al deze niet-opgeslagen wijzigingen vergeten.\n\nWeet je zeker dat je de pagina wilt verlaten?",
    "GridFieldBulkTools.EDIT_CHANGED": "Aangepast",
    "GridFieldBulkTools.EDIT_UPDATED": "Opgeslagen",
    "GridFieldBulkManager.BULKACTION_EMPTY_SELECT": "U moet minstens een item te selecteren.",
    "GridFieldBulkManager.CONFIRM_DESTRUCTIVE_ACTION": "De gegevens zullen permanent verloren. Weet je zeker dat je de pagina wilt verlaten?"
});
}