name: Keepalive

on:
  # At 3:15 AM UTC, on day 16 of the month
  schedule:
    - cron: '15 3 16 * *'
  workflow_dispatch:

permissions: {}

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the colymba account
    if: (github.event_name == 'schedule' && github.repository_owner == 'colymba') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
